name: Bundle Size Check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

defaults:
  run:
    working-directory: my-third-next-app

env:
  BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
  CI_REPO_OWNER: kirandash
  CI_REPO_NAME: nextjs-production-infrastructure
  CI_COMMIT_SHA: ${{ github.sha }}
  CI_BRANCH: master

permissions:
  contents: read
  actions: read
  pull-requests: write

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: my-third-next-app/package-lock.json

      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: true

      - name: Install dependencies
        run: pnpm install

      - name: Restore next build
        uses: actions/cache@v4
        with:
          path: my-third-next-app/.next
          key: ${{ runner.os }}-next-build-${{ hashFiles('my-third-next-app/next.config.js') }}
          restore-keys: |
            ${{ runner.os }}-next-build-

      - name: Build project
        run: pnpm run build

      - name: Check bundle size
        run: pnpm run bundlewatch
